name: Release process

on:
  push:
    tags:
      - v[0-9]*

permissions:
  contents: read
  issues: write

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install packages
        run: npm ci
      - name: unit tests
        run: npm run test
      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps
      - name: Run Playwright tests
        run: CI=true npx playwright test --project=chromium

  create-issue:
    name: release
    runs-on: ubuntu-latest
    needs: tests
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Setup node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "18.x"

      - name: create changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          writeToFile: false


      - name: Запуск скрипта create_issue
        env:
          TAG_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ github.token }}
        run: |
          TITLE="Release ${{ github.ref_name }}"
          BODY=$(cat << 'EOF'

          # Release ${{ github.ref_name }}

          Автор релиза: @${{ github.actor }}
          Дата релиза: ${{ github.event.head_commit.timestamp }}
          Версия релиза: ${{ github.ref_name }}

          ## CHANGELOG
          ${{ steps.changelog.outputs.changes }}

          EOF
          )

          ISSUE_ID=$(gh issue list --json number,title -q \
            ".[] | select(.title == \"$TITLE\") | .number")
          if [ "$ISSUE_ID" != "null" ]; then
            gh issue edit $ISSUE_ID --body "$BODY"
          else
            gh issue create --title "$TITLE" --body "$BODY" --assignee ${{ github.actor }} --label "release notes"
          fi
